### ISSUE TITLE
onSnapshot and onPatches fail when called from an external module

### ISSUE THREAD

**Issue by gouldingken** [xaviergonz/mobx-keystone#443]
I have a working solution in a typescript project. When I watch for changes using onSnapshot and onPatches within that project, it works perfectly. However when I move the exact same code to a library and include it, the method fails with the following error:
`Error: subtreeRoot must be a tree node (usually a model or a shallow / deep child part of a model 'data' object)`

I thought there might be a version clash between the keystone dependencies, but I have tried used peer dependencies as well as ensuring that the referenced versions are identical.

When I debug I can confirm that the issue is arising because tweakedObjects in the local instance contains the object, but when used as a module, it does not. It looks like these WeakMaps are being declared at the module root. If that's the case then I guess it makes sense why keystone wouldn't work correctly across modules. Does anyone know how to address this issue?

Call stack:
```
subscribe.ts:239 Error: subtreeRoot must be a tree node (usually a model or a shallow / deep child part of a model 'data' object)
    at failure (mobx-keystone.es.mjs:86:1)
    at assertTweakedObject (mobx-keystone.es.mjs:387:1)
    at onPatches (mobx-keystone.es.mjs:2872:1)
```

**Comment by gouldingken** [comment]
1.22.18

**Comment by xaviergonz** [comment]
I'm afraid without an example project or something I can't help much.
If you are using yarn v1 then setting mobx-keystone as peer dependency on your dependency and setting it as dependency on the main app should be enough for it to only use one version (you can just check there should be a single instance in the root node_modules.

If you are using yarn v3 then you need to hoist it manually, this is, set it as peer dep in both packages (the lib and the app) and adding it as a dep to the root package.json. Actually you may try to do that with yarn v1 too, maybe it will work.

**Comment by gouldingken** [comment]
I can try to put together a simple example to demonstrate the issue. Do you have any examples where the lib approach works?

**Comment by xaviergonz** [comment]
I've seen it working, but on private code.
If you still have this issue a github project / sandbox that shows this would help indeed.
