### ISSUE TITLE
Getting 'extendObservable' only accepts plain objects as second argument

### ISSUE THREAD

**Issue by casparss** [xaviergonz/mobx-keystone#540]
Package.json
"mobx": "6.12.0",
"mobx-keystone": "^1.9.0",
"mobx-react-lite": "^4.0.6",

Callstack:
[MobX] 'extendObservable' only accepts plain objects as second argument
    at die (http://localhost:3000/static/js/bundle.js:18780:11)
    at extendObservable (http://localhost:3000/static/js/bundle.js:21446:7)
    at http://localhost:3000/static/js/bundle.js:19820:14
    at initObservable (http://localhost:3000/static/js/bundle.js:24145:12)
    at Function.object (http://localhost:3000/static/js/bundle.js:19819:12)
    at new BaseModel (http://localhost:3000/static/js/bundle.js:69012:75)
    at new ThisModel (http://localhost:3000/static/js/bundle.js:71254:24)
    at new RootStore (http://localhost:3000/static/js/bundle.js:839:101)
    at Object.construct (http://localhost:3000/static/js/bundle.js:71446:22)
    at createStore (http://localhost:3000/static/js/bundle.js:705:17)

**Comment by casparss** [comment]
None issue, my error, closing.
